# Generated by Django 5.1.5 on 2025-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_profile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funds_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
