# Generated by Django 5.1.5 on 2025-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_profile_funds_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sum_of_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
