# Generated by Django 5.1.5 on 2025-02-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('sold', 'Sold'), ('unsold', 'Unsold')], default='unsold', max_length=20),
        ),
    ]
